module.exports={
    entry:{
        'app':'./src/app.ts'
    },
    output:{
        filename:'[name].bunele.js'
    },
    module:{
        rules:[
            {
                test:/\.ts$/,
                use:{
                    loader:'ts-loader'
                }
            }
        ]
    }
}